<?php

use App\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Only seed if we don't have any records
        if (sizeof(Course::all()) > 0)
        {
            return;
        }

        $courses = array(
            ['name' => 'Advanced Aviation Knowledge', 'code' => 'AAK'],
            ['name' => 'Aircraft Construction Class 1', 'code' => 'AC1', 'active' => false],
            ['name' => 'Aircraft Construction Class 2', 'code' => 'AC2'],
            ['name' => 'Aircraft Construction Class 3 ', 'code' => 'AC3'],
            ['name' => 'Administration Class 1', 'code' => 'ADM1'],
            ['name' => 'Administration Class 2', 'code' => 'ADM2'],
            ['name' => 'Administration Class 3', 'code' => 'ADM3'],
            ['name' => 'Aircraft Engines Class 1', 'code' => 'AE1'],
            ['name' => 'Aircraft Engines Class 2', 'code' => 'AE2'],
            ['name' => 'Aircraft Engines Class 3', 'code' => 'AE3'],
            ['name' => 'Aircraft Modelling Class 4', 'code' => 'AM4'],
            ['name' => 'Aircraft Modelling (Balsa) Class 1', 'code' => 'AMB1'],
            ['name' => 'Aircraft Modelling (Balsa) Class 2', 'code' => 'AMB2'],
            ['name' => 'Aircraft Modelling (Balsa) Class 3', 'code' => 'AMB3'],
            ['name' => 'Aircraft Modelling (Plastic) Class 1', 'code' => 'AMP1'],
            ['name' => 'Aircraft Modelling (Plastic) Class 2', 'code' => 'AMP2'],
            ['name' => 'Aircraft Modelling (Plastic) Class 3', 'code' => 'AMP3'],
            ['name' => 'Aircraft Radio Class 1', 'code' => 'AR1'],
            ['name' => 'Aircraft Radio Class 2', 'code' => 'AR2', 'active' => false],
            ['name' => 'Aircraft Radio Class 3', 'code' => 'AR3'],
            ['name' => 'Aircraft Recognition Class 1', 'code' => 'AREC1', 'active' => false],
            ['name' => 'Aircraft Recognition Class 2', 'code' => 'AREC2'],
            ['name' => 'Aircraft Recognition Class 3', 'code' => 'AREC3'],
            ['name' => 'Aircraft Recognition Class 4', 'code' => 'AREC4'],
            ['name' => 'Astronomy Class 1', 'code' => 'AST1', 'active' => false],
            ['name' => 'Astronomy Class 2', 'code' => 'AST2'],
            ['name' => 'Astronomy Class 3', 'code' => 'AST3'],
            ['name' => 'Astronomy Class 4', 'code' => 'AST4'],
            ['name' => 'Electronics Class 1', 'code' => 'ELE1'],
            ['name' => 'Electronics Class 2', 'code' => 'ELE2'],
            ['name' => 'Electronics Class 3', 'code' => 'ELE3'],
            ['name' => 'Flight Attendant', 'code' => 'FLATT'],
            ['name' => 'General Knowledge Class 1', 'code' => 'GK1'],
            ['name' => 'General Knowledge Class 2', 'code' => 'GK2'],
            ['name' => 'General Knowledge Class 3', 'code' => 'GK3'],
            ['name' => 'General Knowledge Class 4', 'code' => 'GK4'],
            ['name' => 'Gliding and Soaring Theory', 'code' => 'GLI'],
            ['name' => 'General Proficiency Class 1', 'code' => 'GP1'],
            ['name' => 'General Proficiency Class 2', 'code' => 'GP2'],
            ['name' => 'General Proficiency Class 3', 'code' => 'GP3'],
            ['name' => 'General Proficiency Class 4', 'code' => 'GP4'],
            ['name' => 'General Proficiency Class 5', 'code' => 'GP5'],
            ['name' => 'General Proficiency Class 6', 'code' => 'GP6'],
            ['name' => 'Home Cooking', 'code' => 'HC'],
            ['name' => 'Induction Course', 'code' => 'IDC'],
            ['name' => 'Knitting Class 2', 'code' => 'KN2'],
            ['name' => 'Knitting Class 3', 'code' => 'KN3'],
            ['name' => 'Meteorology Class 1', 'code' => 'MET1'],
            ['name' => 'Meteorology Class 2', 'code' => 'MET2'],
            ['name' => 'Meteorology Class 3', 'code' => 'MET3'],
            ['name' => 'Meteorology Class 4', 'code' => 'MET4'],
            ['name' => 'Navigation Class 1', 'code' => 'NAV1'],
            ['name' => 'Navigation Class 2', 'code' => 'NAV2'],
            ['name' => 'Navigation Class 3', 'code' => 'NAV3'],
            ['name' => 'Navigation Class 4', 'code' => 'NAV4'],
            ['name' => 'Photography', 'code' => 'PHO'],
            ['name' => 'Physics Class 3', 'code' => 'PHY3'],
            ['name' => 'Public Speaking Class 1', 'code' => 'PS1'],
            ['name' => 'Public Speaking Class 2', 'code' => 'PS2'],
            ['name' => 'Public Speaking Class 3', 'code' => 'PS3'],
            ['name' => 'Semaphore', 'code' => 'SEM'],
            ['name' => 'Space Flight Class 1', 'code' => 'SF1', 'active' => false],
            ['name' => 'Space Flight Class 2', 'code' => 'SF2', 'active' => false],
            ['name' => 'Space Flight Class 3', 'code' => 'SF3'],
            ['name' => 'Signals (Morse Code)', 'code' => 'SIG'],
            ['name' => 'Sewing Class 3', 'code' => 'SW3'],
            ['name' => 'Theory of Flight Class 1', 'code' => 'TF1'],
            ['name' => 'Theory of Flight Class 2', 'code' => 'TF2'],
            ['name' => 'Theory of Flight Class 3', 'code' => 'TF3'],
            ['name' => 'Theory of Flight Class 4', 'code' => 'TF4'],
            ['name' => 'Drill Proficiency Class 1', 'code' => 'DP1'],
            ['name' => 'Drill Proficiency Class 2', 'code' => 'DP2'],
            ['name' => 'Drill Proficiency Class 3', 'code' => 'DP3'],
            ['name' => 'Flag Party', 'code' => 'FP'],
            ['name' => 'Community Awareness Award Level 1', 'code' => 'CAA1'],
            ['name' => 'Community Awareness Award Level 2', 'code' => 'CAA2'],
            ['name' => 'Community Awareness Award Level 3', 'code' => 'CAA3'],
            ['name' => 'Community Awareness Award Level 4', 'code' => 'CAA4'],
            ['name' => 'Community Awareness Award Level 5', 'code' => 'CAA5'],
            ['name' => 'Community Awareness Award Level 6', 'code' => 'CAA6'],
            ['name' => 'Emergency Services', 'code' => 'ES'],
            ['name' => 'First Aid Class 1', 'code' => 'FAID1'],
            ['name' => 'First Aid Class 2', 'code' => 'FAID2'],
            ['name' => 'First Aid Class 3', 'code' => 'FAID3'],
            ['name' => 'First Aid Class 4', 'code' => 'FAID4'],
            ['name' => 'First Aid Instructor', 'code' => 'FAIDI'],
            ['name' => 'Fieldcraft Class 1', 'code' => 'FC1'],
            ['name' => 'Fieldcraft Class 2', 'code' => 'FC2'],
            ['name' => 'Fieldcraft Class 3', 'code' => 'FC3'],
            ['name' => 'Fieldcraft Class 4', 'code' => 'FC4'],
            ['name' => 'Life Saving Class 1', 'code' => 'LS1'],
            ['name' => 'Life Saving Class 2', 'code' => 'LS2'],
            ['name' => 'Life Saving Class 3', 'code' => 'LS3'],
            ['name' => 'Life Saving Class 4', 'code' => 'LS4'],
            ['name' => 'Life Saving Instructor', 'code' => 'LSI'],
            ['name' => 'Physical Activities Class 1', 'code' => 'PA1'],
            ['name' => 'Physical Activities Class 2', 'code' => 'PA2'],
            ['name' => 'Physical Activities Class 3', 'code' => 'PA3'],
            ['name' => 'Physical Activities Class 4', 'code' => 'PA4'],
            ['name' => 'Physical Activities Instructor', 'code' => 'PAI1'],
            ['name' => 'Physical Activities Instructor Class 2', 'code' => 'PAI2'],
            ['name' => 'Physical Activities Instructor Class 2', 'code' => 'PI2'],
            ['name' => 'Air Activities - Aviation Experience Class 1', 'code' => 'AAAE1'],
            ['name' => 'Air Activities - Aviation Experience Class 2', 'code' => 'AAAE2'],
            ['name' => 'Air Activities - Aviation Experience Class 3', 'code' => 'AAAE3'],
            ['name' => 'Air Activities - Powered Class 1', 'code' => 'AAP1'],
            ['name' => 'Air Activities - Powered Class 2', 'code' => 'AAP2'],
            ['name' => 'Air Activities - Powered Class 3', 'code' => 'AAP3'],
            ['name' => 'Air Activities - Powered Class 4', 'code' => 'AAP4'],
            ['name' => 'Bass Drummer Class 1', 'code' => 'BDR1'],
            ['name' => 'Bass Drummer Class 2', 'code' => 'BDR2'],
            ['name' => 'Bass Drummer Class 3', 'code' => 'BDR3'],
            ['name' => 'Bugler Class 1', 'code' => 'BGL1'],
            ['name' => 'Bugler Class 2', 'code' => 'BGL2'],
            ['name' => 'Bugler Class 3', 'code' => 'BGL3'],
            ['name' => 'Snare Drummer Class 1', 'code' => 'SDR1'],
            ['name' => 'Snare Drummer Class 2', 'code' => 'SDR2'],
            ['name' => 'Snare Drummer Class 3', 'code' => 'SDR3'],
            ['name' => 'Tenor Drummer Class 1', 'code' => 'TDR1'],
            ['name' => 'Tenor Drummer Class 2', 'code' => 'TDR2'],
            ['name' => 'Tenor Drummer Class 3', 'code' => 'TDR3'],
        );

        foreach($courses as $c)
        Course::create(
            $c
        );
    }
}
